#!/usr/bin/env node
// Vendors the Very Good FFmpeg SDK source into nodes/Vgf/vendor/sdk.
// Run intermittently when the upstream SDK changes: `pnpm sync-sdk`.

import { mkdir, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

const REPO = 'verygoodffmpeg/Very-Good-FFmpeg-Typescript-SDK';
const REF = process.env.SDK_REF ?? 'master';
const FILES = ['src/index.ts', 'src/types.ts', 'src/error.ts'];
const OUT_DIR = join(process.cwd(), 'nodes', 'Vgf', 'vendor', 'sdk');

async function fetchFile(path) {
	const url = `https://raw.githubusercontent.com/${REPO}/${REF}/${path}`;
	const res = await fetch(url);
	if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
	return res.text();
}

async function main() {
	await rm(OUT_DIR, { recursive: true, force: true });
	await mkdir(OUT_DIR, { recursive: true });

	for (const file of FILES) {
		let content = await fetchFile(file);
		// CommonJS tsconfig can't resolve ESM `.js` import specifiers to local `.ts`.
		content = content.replace(/from "(\.\/[^"]+)\.js"/g, 'from "$1"');
		// n8n-node tsconfig omits the DOM lib, so `BodyInit` is undefined; widen to `any`
		// and silence the resulting no-explicit-any lint on that line.
		content = content.replace(
			/( +)(body: data as) BodyInit,/g,
			'$1// eslint-disable-next-line @typescript-eslint/no-explicit-any\n$1$2 any,',
		);
		const basename = file.replace(/^src\//, '');
		await writeFile(join(OUT_DIR, basename), content);
		console.log(`✓ ${basename}`);
	}

	const header = `// Auto-generated by scripts/sync-sdk.mjs from ${REPO}@${REF}.\n// Do not edit by hand; re-run \`pnpm sync-sdk\` to refresh.\n`;
	await writeFile(join(OUT_DIR, 'README.md'), `${header}\nVendored source for the @verygoodffmpeg/sdk runtime, inlined to satisfy n8n Cloud community-node restrictions (no external deps).\n`);
	console.log(`\nVendored SDK source from ${REPO}@${REF} into ${OUT_DIR}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
